"""corrige restricoes da tabela de usuarios

Revision ID: e52cde187c40
Revises: 43c9eaaf5ebe
Create Date: 2026-10-03 17:57:06.730042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52cde187c40'
down_revision: Union[str, Sequence[str], None] = '43c9eaaf5ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_usuarios_nome'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_nome'), ['nome'], unique=1)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
