"""esquema inicial consultores e atendimentos

Revision ID: f0ac3195dcea
Revises: 
Create Date: 2026-10-02 18:49:57.087068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ac3195dcea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('consultores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultores_id'), ['id'], unique=False)

    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(), nullable=False),
    sa.Column('data_atendimento', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['consultor_id'], ['consultores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendimentos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendimentos_id'))

    op.drop_table('atendimentos')
    with op.batch_alter_table('consultores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultores_id'))

    op.drop_table('consultores')
    # ### end Alembic commands ###
